id: P001742
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23700
  title: བདེན་གཉིས་ཀྱི་རྣམ་བཞག་ལེགས་བཤད་དཔྱིད་ཀྱི་དཔལ་མོའི་གླུ་དབྱངས།
  author: ''
  volumes:
    b8e01c8823734deeaacecd99e110be36:
      image_group_id: I1KG23787
      title: ''
      volume_number: 1
      total_pages: 254
      base_file: v001.txt
