id: ID80CD707
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T07:29:34+00:00'
last_modified: '2022-06-07T14:53:58.984648+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23700
  title: བདེན་གཉིས་ཀྱི་རྣམ་བཞག་ལེགས་བཤད་དཔྱིད་ཀྱི་དཔལ་མོའི་གླུ་དབྱངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    '8326':
      image_group_id: I1KG23787
      title: ''
      total_pages: 254
      order: 1
      base_file: 8326.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
